use bitcoin::network::constants::Network;
use bitcoin::secp256k1::Secp256k1;
use bitcoin::util::bip32::{DerivationPath, ExtendedPrivKey, ExtendedPubKey};
use std::io::Write;
use std::str::FromStr;
use crate::transaction::coin_type;


/// Returns the 4-byte master fingerprint of the wallet as a hex string.
/// This uniquely identifies the wallet without revealing any private information.
pub fn get_fingerprint(root_key: &ExtendedPrivKey) -> String {
    let secp = Secp256k1::new();
    let xpub = ExtendedPubKey::from_priv(&secp, root_key);
    hex::encode(xpub.fingerprint().as_bytes())
}

/// Derives the account-level extended public key at m/84'/{coin}'/0'.
/// This xpub can generate all receive and change addresses but CANNOT sign.
pub fn get_account_xpub(root_key: &ExtendedPrivKey, network: Network) -> Result<String, String> {
    let secp = Secp256k1::new();
    let coin = coin_type(network);

    let path = DerivationPath::from_str(&format!("m/84'/{}'/0'", coin))
        .map_err(|e| e.to_string())?;
    let account_key = root_key
        .derive_priv(&secp, &path)
        .map_err(|e| e.to_string())?;
    let xpub = ExtendedPubKey::from_priv(&secp, &account_key);
    Ok(xpub.to_string())
}

/// Returns a standard output descriptor for the wallet's external receive chain.
/// Format: wpkh(xpub/0/*) — compatible with Electrum, Sparrow, Bitcoin Core.
pub fn get_descriptor(root_key: &ExtendedPrivKey, network: Network) -> Result<String, String> {
    let xpub = get_account_xpub(root_key, network)?;
    Ok(format!("wpkh({}/0/*)", xpub))
}

/// Writes the xpub and descriptor to watch_wallet.txt.
/// This file is safe to store on a hot machine — it cannot spend funds.
pub fn export_watch_wallet(root_key: &ExtendedPrivKey, network: Network, save_path: &str) -> Result<(), String> {
    let xpub = get_account_xpub(root_key, network)?;
    let descriptor = get_descriptor(root_key, network)?;
    let fingerprint = get_fingerprint(root_key);
    let net_label = if network == Network::Bitcoin { "mainnet" } else { "testnet" };

    let contents = format!(
        "# Watch-only wallet — generated by BOMA Cold Wallet v0.3\n\
         # Network: {net_label}\n\
         # Master fingerprint: {fingerprint}\n\
         # Import this xpub into Electrum, Sparrow, or Specter to track balances.\n\
         # This file CANNOT spend funds.\n\n\
         xpub={xpub}\n\n\
         descriptor={descriptor}\n"
    );

    let mut f = std::fs::File::create(save_path)
        .map_err(|e| format!("Failed to create {}: {}", save_path, e))?;
    f.write_all(contents.as_bytes())
        .map_err(|e| format!("Failed to write {}: {}", save_path, e))?;

    Ok(())
}

/// Writes the output descriptor to wallet_descriptor.txt.
pub fn export_descriptor(root_key: &ExtendedPrivKey, network: Network, save_path: &str) -> Result<(), String> {
    let descriptor = get_descriptor(root_key, network)?;
    let mut f = std::fs::File::create(save_path)
        .map_err(|e| format!("Failed to create {}: {}", save_path, e))?;
    f.write_all(format!("{}\n", descriptor).as_bytes())
        .map_err(|e| format!("Failed to write descriptor: {}", e))?;
    Ok(())
}
